### ISSUE TITLE
fastFVA is not compatible with CPLEX1210

### ISSUE THREAD

**Issue by liuhl22** [Yu-sysbio/Tutorials-of-metabolic-modeling#1]
It would be better to add another FVA in Fluxestimation.m for users with CPLEX1210 or gurobi.

**Comment by liuhl22** [comment]
%% FVA计算每个反应的最大和最小值
% FVA能给出在满足当前约束时每个反应的最大值和最小值
[minFlux_ph6, maxFlux_ph6, ~] = fluxVariability(model_ph6);
[minFlux_ph55, maxFlux_ph55, ~] = fluxVariability(model_ph55);

**Comment by Yu-sysbio** [comment]
Fixed as suggested
